### PR TITLE
Feat/sub navlinks

### PR DESCRIPTION
**Pull request by ptbarnum4**
- add promo links below nav
image

- remove info session link on high school pages
image

- add opspark promo video to info session page + move hs info below form
image

### CODE REVIEW

**Comment by harveysanders** [comment]
Screen Shot 2022-08-01 at 10 30 16 AM

I don't think these promo links should be sticky. On mobile, the promos + the stick nav bar take up a ton of real estate. Maybe the nav bar should not be there on mobile? I'm not sure of the best solution, but IMO both can't be sticky on mobile. 
What do you think?

Sidenote, we need to get a breakdown of traffic to the site. Is there an analytics tag in there?

**Comment by ptbarnum4** [comment]
I agree that it takes up too much space on mobile. This has been a difficult issue to solve for some reason. 

No we do not have an analytics tag in there

**Comment by harveysanders** [comment]
I think it is okay to completely remove the nav bar and leave the hamburger. We may need a second opinion though.

**Comment by ptbarnum4** [comment]
let's discuss at standup today

**Comment by ptbarnum4** [comment]
image

**Pull request merged**
